version: '3.5'

services:
  db:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
  node:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/nodejs
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ${PWD}/:/var/www/html/:cached